version: "3.9"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-local
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app:
    build: .
    container_name: dogs-app
    restart: always
    depends_on:
      - mysql-db
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      DB_HOST: mysql-db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"

volumes:
  mysql_data:
